### ISSUE TITLE
Multiple Vary: Accept-Encoding Headers

### ISSUE THREAD

**Issue by farmison** [pagespeed/ngx_pagespeed#1325] opened 2016-11-23 12:21 UTC
I'm pretty sure that this is an Nginx PageSpeed issue. 

For some reason, requests for some of our assets (images, css and js) result in a 503 error being returned from Varnish (proxy).

The varnishlog returns 

```
*   << Request  >> 198991
-   Begin          req 198990 rxreq
-   Timestamp      Start: 1479903325.366153 0.000000 0.000000
-   Timestamp      Req: 1479903325.366153 0.000000 0.000000
-   ReqStart       127.0.0.1 39562
-   ReqMethod      GET
-   ReqURL         /css/bootstrap.min.css
-   ReqProtocol    HTTP/1.0
-   ReqHeader      X-Real-IP: 85.115.54.202
-   ReqHeader      X-Forwarded-For: 85.115.54.202
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-Port: 443
-   ReqHeader      Host: ********
-   ReqHeader      Connection: close
-   ReqHeader      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
-   ReqHeader      Accept: text/css,*/*;q=0.1
-   ReqHeader      Referer: https://*********/checkout/login
-   ReqHeader      Accept-Encoding: gzip, deflate, sdch, br
-   ReqHeader      Accept-Language: en-US,en;q=0.8
-   ReqHeader      Cookie: cib_4565616471828769722=0; ex_cib_4565616471828769722=Tue, 21 Feb 2017 10:59:13 GMT; vib_4036072113170809035=1; ex_vib_4036072113170809035=Tue, 21 Feb 2017 10:59:26 GMT; farmison=e212vqv8mc57fpqf3n2ufdmmh5; farmison_basket=8d7f4067-b8c7-45b9-bf59
-   ReqUnset       X-Forwarded-For: 85.115.54.202
-   ReqHeader      X-Forwarded-For: 85.115.54.202, 127.0.0.1
-   VCL_call       RECV
-   ReqHeader      PS-CapabilityList: fully general optimizations only
-   ReqUnset       Cookie: cib_4565616471828769722=0; ex_cib_4565616471828769722=Tue, 21 Feb 2017 10:59:13 GMT; vib_4036072113170809035=1; ex_vib_4036072113170809035=Tue, 21 Feb 2017 10:59:26 GMT; farmison=e212vqv8mc57fpqf3n2ufdmmh5; farmison_basket=8d7f4067-b8c7-45b9-bf59
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate, sdch, br
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Debug          "XXXX MISS"
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 198992 fetch
-   Timestamp      Fetch: 1479903325.368258 0.002105 0.002105
-   RespProtocol   HTTP/1.1
-   RespStatus     503
-   RespReason     Backend fetch failed
-   RespHeader     Date: Wed, 23 Nov 2016 12:15:25 GMT
-   RespHeader     Server: Varnish
-   RespHeader     Content-Type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   RespHeader     X-Varnish: 198991
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   VCL_return     deliver
-   Timestamp      Process: 1479903325.368278 0.002125 0.000020
-   RespHeader     Content-Length: 283
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: close
-   Timestamp      Resp: 1479903325.368314 0.002161 0.000036
-   Debug          "XXX REF 2"
-   ReqAcct        1079 0 1079 250 283 533
-   End
**  << BeReq    >> 198992
--  Begin          bereq 198991 fetch
--  Timestamp      Start: 1479903325.366203 0.000000 0.000000
--  BereqMethod    GET
--  BereqURL       /css/bootstrap.min.css
--  BereqProtocol  HTTP/1.0
--  BereqHeader    X-Real-IP: 85.115.54.202
--  BereqHeader    X-Forwarded-Proto: https
--  BereqHeader    X-Forwarded-Port: 443
--  BereqHeader    Host: *********
--  BereqHeader    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
--  BereqHeader    Accept: text/css,*/*;q=0.1
--  BereqHeader    Referer: https://*********/checkout/login
--  BereqHeader    Accept-Language: en-US,en;q=0.8
--  BereqHeader    X-Forwarded-For: 85.115.54.202, 127.0.0.1
--  BereqHeader    PS-CapabilityList: fully general optimizations only
--  BereqHeader    Accept-Encoding: gzip
--  BereqProtocol  HTTP/1.1
--  BereqHeader    X-Varnish: 198992
--  VCL_call       BACKEND_FETCH
--  VCL_return     fetch
--  BackendOpen    18 default(127.0.0.1,,8000) 127.0.0.1 49396
--  Backend        18 default default(127.0.0.1,,8000)
--  Timestamp      Bereq: 1479903325.366290 0.000087 0.000087
--  BogoHeader     Too many headers: Vary: Accept-Encodin
--  HttpGarbage    "HTTP/1.1%00200%00OK%00%0aServer: nginx/1.8.1%00%0aContent-Type: text/css%00%0aConnection: keep-alive%00%0aETag: W/"582d885b-1c99e"%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary%00"
--  BerespStatus   503
--  BerespReason   Service Unavailable
--  FetchError     http format error
--  BackendClose   18 default(127.0.0.1,,8000)
--  Timestamp      Beresp: 1479903325.368210 0.002007 0.001920
--  Timestamp      Error: 1479903325.368215 0.002012 0.000005
--  BerespProtocol HTTP/1.1
--  BerespStatus   503
--  BerespReason   Service Unavailable
--  BerespReason   Backend fetch failed
--  BerespHeader   Date: Wed, 23 Nov 2016 12:15:25 GMT
--  BerespHeader   Server: Varnish
--  VCL_call       BACKEND_ERROR
--  BerespHeader   Content-Type: text/html; charset=utf-8
--  BerespHeader   Retry-After: 5
--  VCL_return     deliver
--  Storage        malloc Transient
--  ObjProtocol    HTTP/1.1
--  ObjStatus      503
--  ObjReason      Backend fetch failed
--  ObjHeader      Date: Wed, 23 Nov 2016 12:15:25 GMT
--  ObjHeader      Server: Varnish
--  ObjHeader      Content-Type: text/html; charset=utf-8
--  ObjHeader      Retry-After: 5
--  Length         283
--  BereqAcct      515 0 515 5586 0 5586
--  End
```

For some reason, it appears that Pagespeed is adding multiple Accept-Encoding headers - so many that Varnish cannot process the response - 

```
--  BogoHeader     Too many headers: Vary: Accept-Encodin
--  HttpGarbage    "HTTP/1.1%00200%00OK%00%0aServer: nginx/1.8.1%00%0aContent-Type: text/css%00%0aConnection: keep-alive%00%0aETag: W/"582d885b-1c99e"%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary: Accept-Encoding%00%0aVary%00"
```

This occurs for seemingly random files at random times.

**Comment by oschaaf** [comment] 2016-11-24 07:46
There's an earlier issue filed for this here https://github.com/pagespeed/ngx_pagespeed/issues/1064

The issue is fixed on both the ngx_pagespeed and PSOL side, but there's no ngx_pagespeed release based on the fixed PSOL version yet.

In that issue I posted a patch that suppresses the symptoms:
https://gist.githubusercontent.com/oschaaf/c16c7458a57db4e94323/raw/a659f3809b22a89b49cd647d5466ab8f8fa66dad/multiple-vary-hans-hotfix.patch

Let me know if that works for you.

Closing this issue (because it was already addressed on the bleeding edge)

**Closed by oschaaf** 2016-11-24 07:46 UTC
