### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by liewzy** [pagespeed/ngx_pagespeed#1173] opened 2016-04-07 08:06 UTC
What's wrong will make users "suddenly" unable login and add to cart? 
The request show net::ERR_SPDY_PROTOCOL_ERROR in dev console. Most likely anything work in the background that interact with database will result in timeout error. 
However, all content pages and files are loaded normally. 
I tried delete all filters (leave default)but it still won't work. 
If pagespeed turned off, everything back to normal. 
This suddenly happens today, was working fine previously, I'm using HTTPS with pagespeed version 1.10.33.7 in ubuntu 14.04 server.

**Comment by oschaaf** [comment] 2016-04-07 08:08
@liewzy Could you patch in https://github.com/pagespeed/ngx_pagespeed/pull/1147 and see if that resolves the problem?

**Comment by Angristan** [comment] 2016-04-09 17:25
Experienced this today. Searched for hours why my WP admin didn't work. Finally disabled ngx_pagespeed.

**Comment by amourinho** [comment] 2016-04-10 20:20
This may be the exact same issue I've been having with my setup. 
[https://github.com/pagespeed/ngx_pagespeed/issues/1175](url)

The timeout error I get is ERR_SPDY_PROTOCOL_ERROR
Can you verify that even a simple form like the one I created gives you this error?

**Comment by liewzy** [comment] 2016-04-11 01:26
Unfortunately It's out of my ability. I'm using serverpilot to setup my ngnix server and it auto update and patch my server for security.

**Comment by oschaaf** [comment] 2016-04-12 22:39
Closing this issue as a duplicate of https://github.com/pagespeed/ngx_pagespeed/issues/1175

**Closed by oschaaf** 2016-04-12 22:39 UTC
Labels: duplicate
