### ISSUE TITLE
Serf status 113: image rewrites end up in 404 errors.

### ISSUE THREAD

**Issue by benhartwich** [pagespeed/ngx_pagespeed#1267] opened 2016-09-09 08:46 UTC
Hi,

I´ve got the problem, that pagespeed brokes the image rewrites (www.currywursttest.com), which causes in 404 errors at my page. This happens after page speed runs a few days. I don´t know if the serf status 113 is related to this problems, but it seems to.

How can I debug this problem further? 
nginx version: nginx/1.10.1 (Debian 8)

My configuration is: 

```
pagespeed on;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed FileCacheSizeKb            102400;
pagespeed FileCacheCleanIntervalMs   3600000;
pagespeed FileCacheInodeLimit        500000;
pagespeed MessageBufferSize 100000;
pagespeed LowercaseHtmlNames on;
pagespeed PreserveUrlRelativity on;
pagespeed RewriteLevel CoreFilters;
pagespeed InPlaceResourceOptimization on;
pagespeed DisableRewriteOnNoTransform off;
pagespeed RespectVary on;
pagespeed FetchHttps enable;
pagespeed HttpCacheCompressionLevel 9;
pagespeed CustomFetchHeader Accept-Encoding gzip;
pagespeed Domain cdn.podlove.org;
pagespeed CssInlineMaxBytes 8000;
pagespeed EnableFilters prioritize_critical_css,inline_preview_images,lazyload_images,insert_dns_prefetch,inline_google_font_css,lazyload_images;
pagespeed EnableCachePurge on;
pagespeed ShardDomain https://www.currywursttest.com https://static.currywursttest.com,https://static2.currywursttest.com;

pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;
pagespeed StatisticsLoggingIntervalMs 60000;
pagespeed StatisticsLoggingMaxFileSizeKb 1024;

location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }

pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;
pagespeed GlobalAdminPath /pagespeed_global_admin;
```

**Comment by oschaaf** [comment] 2016-09-09 11:22
I could reproduce the problem, but then I requested https://www.currywursttest.com/?PageSpeedFilters=rewrite_images and the 404's went away. The 404's now also are gone at https://www.currywursttest.com

There have been earlier similar reports:

https://groups.google.com/forum/#!msg/mod-pagespeed-discuss/hDLytDrE834/B-VdsLwiAgAJ

https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/lNtYJyPL9mI

Perhaps figuring out what Serf status 113 means will give a clue about what the problem is.

**Comment by benhartwich** [comment] 2016-09-09 11:32
Thank you. Is it critical that PageSpeedFilters could be executed by everyone?

Where do I find, what serf status 113 means? Google doesn´t tell my anything about it.

**Comment by oschaaf** [comment] 2016-09-09 11:44
I was looking into the same, figuring out Serf's status codes doesn't seem to be straightforward.
@jeffkaufman looked into resolving Serf's error codes earlier, see https://www.jefftk.com/p/serf-error-codes. But that regrettably does not mention status code 113.

At the moment I don't understand yet how such a low number could be logged -- but a guess is that if `APR_OS_START_USERERR` equals zero in your case, 113 would equal `SERF_ERROR_WAIT_CONN`

```
#define SERF_ERROR_RANGE 100
#define SERF_ERROR_START (APR_OS_START_USERERR + SERF_ERROR_RANGE)

....

/* This code is for when the connection is blocked - we can not proceed
 * until something happens - generally due to SSL negotiation-like behavior
 * where a write() is blocked until a read() is processed.
 */
#define SERF_ERROR_WAIT_CONN (SERF_ERROR_START + 3)
```

**Comment by oschaaf** [comment] 2016-09-09 11:48
Whoops, please ignore my previous comment, I got confused while following all the places where error definitions occur. That does not add up right at all.

**Comment by benhartwich** [comment] 2016-09-09 12:07
It seems to happen right after reloading nginx. I could reproduce it by now again.

**Comment by oschaaf** [comment] 2017-07-17 17:37
Serf status code 113 translates to `No route to host`. I've seen no other reports mentioning this error code, so I think this was a network issue. Closing this.

**Closed by oschaaf** 2017-07-17 17:37 UTC
