### ISSUE TITLE
404 error on pagespeed optimized ressources

### ISSUE THREAD

**Issue by bluelu** [pagespeed/ngx_pagespeed#1279] opened 2016-09-22 13:06 UTC
After having the module enabled for about 1 day on our webserver, nginx returns 404 responses on random optimized pagespeed ressources, so scripts and images can not be included. (E.g. https://www.test.com/images/test/xnew-05artboard-1.png.pagespeed.ic.AvnAYXxujQ.jpg). 

It's very simliar to https://groups.google.com/forum/#!searchin/ngx-pagespeed-discuss/404$20resources%7Csort:relevance/ngx-pagespeed-discuss/lNtYJyPL9mI/blIHchCmBQAJ

Observations:
- Restarting nginx doesn't solve the issue.
- Deleting the cache resolves the issue
- All our ressources are loaded from https. Maybe that has something to do with it.

Any idea what could cause the issue? We will turn on debug logging. But the issue only seems to appear after a while...

**Comment by jeffkaufman** [comment] 2016-09-22 13:37
Do you have any sort of rate limiting enabled in nginx?

Is there anything in nginx's error log?

**Comment by bluelu** [comment] 2016-09-22 14:49
The requests are handled by an upstream server (nginx acting as reverse proxy). Nginx itself does not have any request limits in place, but we will check if there are any rate limits in place on the upstream servers (I assume though not). However, I don't think that there was more traffic at that time.

The error.log file contains errors of the kind: "[ngx_pagespeed 1.11.33.3-0] Rejected absolute url reference https://... ". Around 7500 for 1 day

We use nginx version: openresty/1.9.3.1.

We will also enable debugging and then try to capture more debugging information next monday.

**Comment by bluelu** [comment] 2016-09-30 07:51
Hi,

Just to give you an update on our side:
- We had one path in our url which was not covered by pagespeed which we disallowed.
- We disabled the image inline module.

We haven't experienced any issues since then anymore. 

I assume it's related to the inline image module somehow together with the optimisation plugins for the images (and maybe some images which didn't had expire timestamps, so they couldn't get optimised/or inlined)

**Comment by bluelu** [comment] 2016-09-30 09:05
The issue came up unfortunately again (just later than before). It seems to be related to the expiring cache. When we purge the cache through the interface, we have the same issue as well. We will investigate.

**Comment by bluelu** [comment] 2016-10-04 14:11
Hi, 

Below is more information. The issue always appears if the cache is invalidated (by timeout or by the pagespeed admin). In this case we don't observer any request to our backend server anymore. As long as the cache is not invalidated, everything works fine.

At first we though it was related to not specifying a MapOriginDomain (since our nginx server also acts as reverse proxy). However this didn't change anything.
Any ideas on what might trigger the issue?

ngx_pagespeed-release-1.11.33.3-beta
nginx version: openresty/1.9.3.1
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled


config:
server {
    listen 80;
    listen 443 ssl spdy;
    server_name cmspreview.abc.com;

    error_log /var/log/nginx/debug-access.log debug;

    include shared/ssl.conf;

    include shared/pagespeed-admin-allow.conf;
    pagespeed on;
    pagespeed MapOriginDomain http://1.2.3.4 https://cmspreview.abc.com www.abc.com;
    pagespeed MapOriginDomain http://1.2.3.4 http://cmspreview.abc.com www.abc.com;
    pagespeed EnableCachePurge on;

    location / {
      pagespeed EnableFilters rewrite_images;
      location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
        add_header "" "";
      }

      location ~ "^/pagespeed_static/" { }
      location ~ "^/ngx_pagespeed_beacon$" { }

      pagespeed Allow "*";

      pagespeed Disallow "*.pagespeed.*";

      pagespeed EnableFilters debug;

      expires $talkwalkercom_expires;

      client_max_body_size 10M; # to upload content to the website
      proxy_pass http://cmstest;
    }



Debug log of nginx related to a 404 ressource after having cleared the cache:
2016/10/04 15:35:12 [debug] 20454#0: *1 process spdy frame head:80030001 f:1 l:489
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy SYN_STREAM frame sid:489 prio:3
2016/10/04 15:35:12 [debug] 20454#0: *1 posix_memalign: 0000000003B1DA30:4096 @16
2016/10/04 15:35:12 [debug] 20454#0: *1 posix_memalign: 0000000003B1EA40:4096 @16
2016/10/04 15:35:12 [debug] 20454#0: *1 process spdy header block 479 of 479
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy inflate out: ni:0000000003A5546F no:0000000003B1EE5F ai:17 ao:0 rc:0
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy header block has 13 entries
2016/10/04 15:35:12 [debug] 20454#0: *1 http uri: "/assets/front-end/media/social/xyoutube.png.pagespeed.ic.4lon_Xis87.webp"
2016/10/04 15:35:12 [debug] 20454#0: *1 http args: ""
2016/10/04 15:35:12 [debug] 20454#0: *1 http exten: "webp"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy alloc large header buffer
2016/10/04 15:35:12 [debug] 20454#0: *1 malloc: 0000000003AE0BA0:8192
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy large header alloc: 0000000003AE0BA0 8192
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy inflate out: ni:0000000003A55480 no:0000000003AE0D83 ai:0 ao:7708 rc:0
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http request line: "GET /assets/front-end/media/social/xyoutube.png.pagespeed.ic.4lon_Xis87.webp HTTP/1.1"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "host: cmspreview.abc.com"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "pragma: no-cache"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "cache-control: no-cache"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "accept: image/webp,image/*,*/*;q=0.8"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "referer: https://cmspreview.abc.com/"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "accept-encoding: gzip, deflate, sdch, br"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "accept-language: en-US,en;q=0.8"
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy http header: "cookie: acceptCookie=1; _GPSLSC=; _ga=GA1.2.1586949462.1474009302; _dc_gtm_UA-28632961-1=1; _mkto_trk=id:538-DCX-400&token:_mch-abc.com-1474880375623-56296; _ga=GA1.3.1586949462.1474009302; laravel_session=eyJpdiI6IkpyNndVRVczb2lEbFhydUZVNmNudGc9PSIsInZhbHVlIjoiSmJ0QjBIU0VBbUhnTk94VnZWdnVuSXUrM3lGMW1nRkF6MmxaV3pqRjc5UVwvQTBEWnlPOGEycjJ4UllGRjFsbEJITUlEdmpKUTRxU1M0UE1PREE3OFhBPT0iLCJtYWMiOiJhODJkNmI3OWE3YjFiZWIxY2IwNTM0Y2RkN2VmNzZlN2E1ZmY1YmJiOTJkNjIxMWZiZmNjYjEyNDI4MjFhYjI2In0%3D"
2016/10/04 15:35:12 [debug] 20454#0: *1 rewrite phase: 0
2016/10/04 15:35:12 [debug] 20454#0: *1 rewrite phase: 1
2016/10/04 15:35:12 [debug] 20454#0: *1 http script value: "robots-cmspreview.txt"
2016/10/04 15:35:12 [debug] 20454#0: *1 http script set $robots_file
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: "/"
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: "ngx_pagespeed_global_statistics"
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: "lserver-health"
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: "lserver-errorlog"
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: "lserver-accesslog"
2016/10/04 15:35:12 [debug] 20454#0: *1 test location: ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+"
2016/10/04 15:35:12 [debug] 20454#0: *1 using configuration "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+"
2016/10/04 15:35:12 [debug] 20454#0: *1 http cl:-1 max:10485760
2016/10/04 15:35:12 [debug] 20454#0: *1 rewrite phase: 3
2016/10/04 15:35:12 [debug] 20454#0: *1 rewrite phase: 4
2016/10/04 15:35:12 [debug] 20454#0: *1 post rewrite phase: 5
2016/10/04 15:35:12 [debug] 20454#0: *1 generic phase: 6
2016/10/04 15:35:12 [debug] 20454#0: *1 generic phase: 7
2016/10/04 15:35:12 [debug] 20454#0: *1 access phase: 8
2016/10/04 15:35:12 [debug] 20454#0: *1 access phase: 9
2016/10/04 15:35:12 [debug] 20454#0: *1 access phase: 10
2016/10/04 15:35:12 [debug] 20454#0: *1 post access phase: 11
2016/10/04 15:35:12 [debug] 20454#0: *1 pagespeed phase: 12
2016/10/04 15:35:12 [debug] 20454#0: *1 http pagespeed handler "/assets/front-end/media/social/xyoutube.png.pagespeed.ic.4lon_Xis87.webp"
2016/10/04 15:35:12 [debug] 20454#0: *1 http cleanup add: 0000000003B1E968
2016/10/04 15:35:12 [error] 20454#0: [ngx_pagespeed 1.11.33.3-0] Rejected absolute url reference https://cmspreview.abc.com/assets/front-end/media/social/youtube.png
2016/10/04 15:35:12 [debug] 20454#0: *1 http finalize request: -4, "/assets/front-end/media/social/xyoutube.png.pagespeed.ic.4lon_Xis87.webp?" a:1, c:2
2016/10/04 15:35:12 [debug] 20454#0: *1 http request count:2 blk:0
2016/10/04 15:35:12 [debug] 20454#0: *1 spdy frame complete pos:0000000003A55480 end:0000000003A55480


served html still contains the optimized version, even though the webp image does not exist anymore.

<img src="https://cmspreview.abc.com/assets/front-end/media/social/xyoutube.png.pagespeed.ic.4lon_Xis87.webp" alt="Youtube" data-pagespeed-url-hash="3039284693" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">

**Comment by aillusions** [comment] 2017-01-02 22:13
having same issue on CentOS 6
RESTY_VERSION=1.11.2.1
RESTY_OPENSSL_VERSION=1.0.2j
NPS_VERSION=1.11.33.4

**Comment by gtk-aschmidt** [comment] 2017-02-03 16:55
I have this problem on two virtual domains. The thing they seem have in common is that they both immediately redirect to the https version of themselves if accessed over http. Also http/2 is enabled.

I haven't identified the same problem on any vanilla http domains, so my first guess is it's some kind of interaction between pagespeed and http/2, but I haven't been able to construct a Google query that confirms any cause and effect, or any possible confusion when http/2 clients and http 1.1 clients try to access the same resources, or any other guess I've been able to think of so far.

**Comment by bluelu** [comment] 2017-02-03 17:40
On our side,  we did not have http 2.0 enabled yet.  However we also
redirect http requests to the https version by default.

**Comment by oschaaf** [comment] 2017-02-04 15:13
It is helpful to know that the problem occurs without http 2.0 enabled, because that rules out a class of potential causes.
I think that one of the lines posted in the logs above is relevant to the problem:

```
[ngx_pagespeed 1.11.33.3-0] Rejected absolute url reference https://... 
```

I suspect that figuring out what triggers the occurrence of that line is key to solving the problem.

**Comment by dgomezs** [comment] 2017-07-08 12:57
Experiencing the same issue now. @bluelu Did you manage to have a workaround?

Thank you in advanced.

**Comment by bluelu** [comment] 2017-07-10 07:01
@dgomezs no, we switched to the apache integration because we didn't get it to work.

**Comment by gogobu** [comment] 2017-07-10 08:39
Setting LoadFromFileMatch solved the problem for me.

**Comment by l-olsem** [comment] 2017-07-12 11:42
Since we  (@bluelu and myself) had pagespeed running in a reverse-proxy setup I don't think LoadFromFileMatch would have helped us, but thanks anyway. We managed to circumvent the issue by running pagespeed upstream.

**Comment by dgomezs** [comment] 2017-07-12 14:36
Thanks for the feedback managed to make it work

**Comment by oschaaf** [comment] 2017-07-27 22:18
The `rejected absolute url reference` messages can be caused by using `pagespeed Disallow *;`  in a configuration that subsequently whitelists what is allowed to be optimized. Combined with output domain rewriting (like initiated by `MapProxyDomain`, it's possible to end up with .pagespeed. resources that cannot be reconstructed on a cold cache. The solution is to use `Allow` to whitelist the origin/path that will be used to fetch the inputs for the .pagespeed. url reconstruction.

Closing this as a duplicate of https://github.com/pagespeed/mod_pagespeed/issues/1155

**Closed by oschaaf** 2017-07-27 22:18 UTC
Labels: duplicate

**Comment by biomedicus** [comment] 2018-09-30 18:04
oschaf i have the same issue , i dont know much about programming,  what allow rule should i use and where should i put it? my images arent showing after speedpage
