### ISSUE TITLE
WordPress visual editor issue with pagespeed

### ISSUE THREAD

**Issue by isaumya** [pagespeed/ngx_pagespeed#1054] opened 2015-11-29 20:17 UTC
Hey guys,
I've been starts using pagespeed on my nginx server and I see a very wired thing after enabling pagespeed with default settings. When I go to wordpress post or page edit section, the visual editor doesnt show up. It looks like this:

![2015-11-30_1-46-07](https://cloud.githubusercontent.com/assets/2124755/11459773/493f02b6-9704-11e5-9754-2c7768daf3bc.jpg)

Any idea why this is happeing and how to fix this?

**Comment by oschaaf** [comment] 2015-11-29 20:29
This looks like a duplicate of https://github.com/pagespeed/ngx_pagespeed/issues/957, which was fixed via https://github.com/pagespeed/ngx_pagespeed/commit/acb89a840cc87969b22e9d9b3449992376af2a40

It looks like the latest release does not include that change, but you could patch that change in yourself to fix the issue (it is a very small patch).

**Comment by isaumya** [comment] 2015-11-29 20:34
Thanks @oschaaf, can you give me the patch link so that I can send it to my server admin and he can install it. Thanks for your kind help.

**Comment by oschaaf** [comment] 2015-11-29 20:38
@isaumya Sure, here you go:
https://github.com/pagespeed/ngx_pagespeed/commit/acb89a840cc87969b22e9d9b3449992376af2a40.patch

**Comment by rfnx** [comment] 2015-12-14 20:02
@oschaaf Hello, do you know when will the patch be included in the releases ? I'm just asking because it was merged so maybe someone forgot to include it ?

Of course I can patch it everytime but most people don't know about the issue and will have the problem if they enable defer_javascript on nginx.

**Comment by isaumya** [comment] 2015-12-14 20:28
@rfnx Good question buddy....

**Comment by oschaaf** [comment] 2015-12-16 09:56
@jeffkaufman should I create a new pull to master based on https://github.com/pagespeed/ngx_pagespeed/commit/acb89a840cc87969b22e9d9b3449992376af2a40 for this?

**Comment by jeffkaufman** [comment] 2015-12-18 16:46
I'll patch this into 1.10.33.2

**Closed** 2015-12-21 16:30 UTC

**Comment by rfnx** [comment] 2015-12-21 16:34
I confirm the patch is now in the latest version : v1.10.33.2-beta ! Thanks :)
