### ISSUE TITLE
4xx status code and The preceding resource was not rewritten because its domain is not authorized

### ISSUE THREAD

**Issue by kjareena** [pagespeed/ngx_pagespeed#1441] opened 2017-07-19 06:10 UTC
Dear Sir,

view-source:https://www.automotive-technology.com/?PageSpeedFilters=+debug

subdomain : https://industry.automotive-technology.com

below are the errors in debug

below is my htaccess files
ExpiresActive On ExpiresByType image/jpg "access 1 year" ExpiresByType image/jpeg "access 1 year" ExpiresByType image/gif "access 1 year" ExpiresByType image/png "access 1 year" ExpiresByType text/css "access 1 month" ExpiresByType text/html "access 1 month" ExpiresByType application/pdf "access 1 month" ExpiresByType text/x-javascript "access 1 month" ExpiresByType application/x-shockwave-flash "access 1 month" ExpiresByType image/x-icon "access 1 year" ExpiresDefault "access 1 month"

#Begin gzip and deflate

AddOutputFilterByType DEFLATE text/html text/css application/x-javascript text/plain text/xml image/x-icon
ModPagespeed on ModPagespeedRewriteLevel CoreFilters ModPagespeed FetchHttps enable

AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html

ModPagespeedEnableFilters debug

#ModPagespeedEnableFilters extend_cache
#ModPagespeedEnableFilters rewrite_css

#ModPagespeedEnableFilters collapse_whitespace
#ModPagespeedEnableFilters remove_comments

ModPagespeedEnableFilters insert_image_dimensions
ModPagespeedEnableFilters resize_images
ModPagespeedEnableFilters rewrite_images
ModPagespeedEnableFilters recompress_images
ModPagespeedEnableFilters resize_mobile_images   

ModPagespeedRespectXForwardedProto on
ModPagespeedDomain https://www.automotive-technology.com
#ModPagespeedDomain https://industry.automotive-technology.com
#ModPagespeedDomain https://www.automotive-technology.com/stylesheet/css
ModPagespeedDomain *.automotive-technology.com

#ModPagespeedMapRewriteDomain https://industry.automotive-technology.com *automotive-technology.com
#ModPagespeedMapRewriteDomain https://industry.automotive-technology.com http://industry.automotive-technology.com

ModPagespeed LoadFromFileMatch https://www.automotive-technology.com/  /home/automotivetechno/public_html/
ModPagespeed LoadFromFileRuleMatch disallow .*
ModPagespeed LoadFromFileRuleMatch allow \.css$
ModPagespeed LoadFromFileRuleMatch allow \.jpe?g$
ModPagespeed LoadFromFileRuleMatch allow \.png$
ModPagespeed LoadFromFileRuleMatch allow \.gif$
ModPagespeed LoadFromFileRuleMatch allow \.js$

ModPagespeedCriticalImagesBeaconEnabled false
ModPagespeedLazyloadImagesAfterOnload off
#ModPagespeedCombineAcrossPaths off

 I am using nginx as proxy server. htaccess rules are working from apache

**Comment by oschaaf** [comment] 2017-07-19 07:34
Closing as a duplicate of https://github.com/pagespeed/mod_pagespeed/issues/1596

**Closed by oschaaf** 2017-07-19 07:34 UTC
Labels: duplicate
