### ISSUE TITLE
Could not rewrite resource in-place because URL is not in cache on static resources

### ISSUE THREAD

**Issue by mqudsi** [pagespeed/ngx_pagespeed#910] opened 2015-02-14 03:26 UTC
I'm having a problem with ngx_pagespeed where it's working like a dream for any proxied or cached resources, but I can't figure out how to get it to do in-place rewrites of static HTML content served by nginx. 

For a plain-Jane html file, this is the first hit:
```
[Sat, 14 Feb 2015 03:42:12 GMT] [Info] [14531] Trying to serve rewritten resource in-place: https://neosmart.net/EasyBCD/easybcd.html
[Sat, 14 Feb 2015 03:42:12 GMT] [Info] [14531] Cache entry is expired: https://neosmart.net/EasyBCD/easybcd.html (fragment=neosmart.net)
[Sat, 14 Feb 2015 03:42:12 GMT] [Info] [14531] Could not rewrite resource in-place because URL is not in cache: https://neosmart.net/EasyBCD/easybcd.html
```

And this is the second:

```
[Sat, 14 Feb 2015 03:42:31 GMT] [Info] [14531] Trying to serve rewritten resource in-place: https://neosmart.net/EasyBCD/easybcd.html
[Sat, 14 Feb 2015 03:42:31 GMT] [Info] [14531] Cache entry is expired: https://neosmart.net/EasyBCD/easybcd.html (fragment=neosmart.net)
[Sat, 14 Feb 2015 03:42:31 GMT] [Info] [14531] Could not rewrite resource in-place because URL is not in cache: https://neosmart.net/EasyBCD/easybcd.html
```

The headers for the file in question:
```
HTTP/1.1 200 OK
Server: nginx/1.7.9
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Strict-Transport-Security: max-age=604800
X-UA-Compatible: IE=Edge,chrome=1
Date: Tue, 27 Jan 1970 01:20:08 GMT
X-Page-Speed: 1.9.32.3-4448
Cache-Control: max-age=0, no-cache
```

Do you have any idea why pagespeed isn't caching the file correctly? There are no messages about file size, origin, etc. that would indicate something's wrong.

**Comment by mqudsi** [comment] 2015-02-14 03:33
I'm guessing this is due to the inability to force ngx_pagespeed to ignore the no-transform header on html files in any way, shape, or form.

**Comment by oschaaf** [comment] 2015-02-14 08:05
@mqudsi This looks like expected behaviour to me.
In-place rewriting does not optimize and/or cache html by itself.
For caching of html, you could have a look at https://developers.google.com/speed/pagespeed/module/downstream-caching
For that to work, the html should be served as cacheable in the first place, and you might have to fix the date header (yours looks odd, does it look like that without ngx_pagespeed?: `Date: Tue, 27 Jan 1970 01:20:08 GMT`)

Closing this, feel free to re-open if you think there's still a problem.

@jeffkaufman as a side note, it looks like these html requests are never marked as "ipro not being applicable" in cache, resulting in a costly lookup all the way to the slowest cache backend in the property cache each time? Should we look into that?

**Closed by oschaaf** 2015-02-14 08:05 UTC

**Comment by mqudsi** [comment] 2015-02-15 13:04
Thanks. Opened as #913

**Comment by mqudsi** [comment] 2015-02-15 16:18
@oschaaf This is odd, but pagespeed is now rewriting the pages in question? As you know, I've been playing around with the ngx_pagespeed config to get things the way I want them, but the HTML is still being served locally, the date header is still wrong, but now `ngx_pagespeed` *is* rewriting the static HTML as I wish it to. As an FYI, I did upgrade to 1.7.10.

This is the new response:
```
HTTP/1.1 200 OK
Server: nginx/1.7.10
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Strict-Transport-Security: max-age=604800
X-UA-Compatible: IE=Edge,chrome=1
Date: Wed, 28 Jan 1970 13:54:19 GMT
X-Page-Speed: 1.9.32.3-4448
Cache-Control: max-age=0, no-cache
```

No real changes to speak of.

**Comment by oschaaf** [comment] 2015-02-16 21:35
@mqudsi I was busy trying to reproduce (no luck yet) and had another look at the two response headers you posted. The first and second example of the `Date:` header value you posted show that it's value actually is being set, but incorrectly. That is remarkable, and worth a closer look.

**Comment by mqudsi** [comment] 2015-02-16 21:39
@oschaaf Yeah I wanted to comment on that at the time, I was going to say the date is wrong but the time isn't but that was of course not the case. 

I'm guessing it actually shows nginx uptime added to epoch?

**Comment by oschaaf** [comment] 2015-02-16 21:54
@mqudsi Possibly, I'm not sure. Are you on a 32 bits platform?

**Comment by mqudsi** [comment] 2015-02-16 21:55
@oschaaf I am indeed.

**Comment by oschaaf** [comment] 2015-02-16 22:19
@mqudsi That confirms my suspicion that using `ngx_current_msec` here was not the best of ideas:
https://github.com/pagespeed/ngx_pagespeed/pull/605/files#diff-8fb776418fb480e5f084e8500b8f0b0cR251

I'll post a patch for this tomorrow.
