### ISSUE TITLE
HttpCacheCompressionLevel only uses gzip, no brotli option

### ISSUE THREAD

**Issue by therealmarv** [pagespeed/ngx_pagespeed#1506] opened 2017-11-23 15:24 UTC
I'm using mostly brotli (on the fly compression) on my server.
The option `HttpCacheCompressionLevel` only stores gzip in cache which results in serving gzip. Can we make it also capable storing brotli internally?

I had to use this [workaround here](https://github.com/pagespeed/ngx_pagespeed/issues/1345#issuecomment-269035274) to get pagespeed+brotli fully working.

**Comment by jmarantz** [comment] 2017-11-23 15:41
Duplicate of https://github.com/pagespeed/mod_pagespeed/issues/1148

**Closed by jmarantz** 2017-11-23 15:41 UTC
