### ISSUE TITLE
For ARMv7 processor

### ISSUE THREAD

**Issue by tornade69** [pagespeed/ngx_pagespeed#1013] opened 2015-10-04 18:43 UTC
Hi,

I use a scaleway VPS but processor are ARMv7 on Debian 8

I can use ngx_pagespeed. How can i do

Thanks

**Comment by crowell** [comment] 2015-10-04 19:24
We currently don't officially support pagespeed on ARM or provide a precompiled PSOL binary.

Some users have successfully compiled PSOL on ARM devices.

You can see the thread here https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/MqQ-QmmaNJM but be aware this unsupported/tested and isn't guaranteed to even compile.

Closing as a duplicate of https://github.com/pagespeed/mod_pagespeed/issues/737

**Closed by crowell** 2015-10-04 19:24 UTC

**Comment by jeffkaufman** [comment] 2016-11-14 16:01
Re-deduped to https://github.com/pagespeed/ngx_pagespeed/issues/1213
