### ISSUE TITLE
memcached stats with nginx 1.9.11 and 1.10.33.5 dynamic module

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1133] opened 2016-02-23 17:38 UTC
I use to see memcached stats in global general stats area prior to update to nginx 1.9.11 and 1.10.33.5 but now turned on per vhost stats and they're always 0 in per vhost statistics ?
```
memcache_error_burst_size	0	0
memcache_last_error_checkpoint_ms	0	0
memcache_timeouts	0	0
memcached_async_deletes	0	0
memcached_async_hits	0	0
memcached_async_inserts	0	0
memcached_async_misses	0	0
memcached_blocking_deletes	0	0
memcached_blocking_hits	0	0
memcached_blocking_inserts	0	0
memcached_blocking_misses	0	0
```
but in physical caches console it shows up as
```
memcached server 127.0.0.1:11211 version 1.4.25 pid 7911 up 2039 seconds 
bytes:                 1265544
bytes_read:            2983049
bytes_written:         2853324
cmd_get:               418
cmd_set:               351
connection_structures: 7
curr_connections:      6
curr_items:            280
evictions:             0
get_hits:              103
get_misses:            315
limit_maxbytes:        25165824
pointer_size:          64
rusage_system:         58991
rusage_user:           64
threads:               4
total_connections:     7
total_items:           351
```
nothing else on the servers uses memcached, so it's all ngx_pagespeed

but `/pagespeed_global_admin/statistics` global stats shows memcached stats
```
memcache_error_burst_size	0	0
memcache_last_error_checkpoint_ms	0	0
memcache_timeouts	0	0
memcached_async_deletes	0	0
memcached_async_hits	33	1
memcached_async_inserts	268	1
memcached_async_misses	220	1
memcached_blocking_deletes	0	0
memcached_blocking_hits	68	1
memcached_blocking_inserts	66	1
memcached_blocking_misses	80	1
```
is memcached stats only available in global statistics and not in per vhost stats ?

**Comment by oschaaf** [comment] 2016-02-24 11:00
@centminmod RE: "is memcached stats only available in global statistics and not in per vhost stats" 

That is correct. When you have the same memcached configuration set up for different vhosts/server{} blocks, the underlying code (and vhosts) will share the same memcached client. Hence any statistics for that are tracked at the global level, and not per-vhost.

I'm closing this issue, assuming you agree that this is not a bug.

**Closed by oschaaf** 2016-02-24 11:00 UTC
