### ISSUE TITLE
Duplicate Headers

### ISSUE THREAD

**Issue by jrahmy** [pagespeed/ngx_pagespeed#314] opened 2013-04-30 23:39 UTC
I have nginx setup to gzip static content:
https://gist.github.com/pathetic/dd4a565907aae718093a

When serving pagespeed resources, I notice the Vary: Accept-encoding value gets duplicated. I saw a similar issue in the tracker but it was marked as fixed and involved a proxy setup.

I also have expires headers set to 1 year in the future for static content:
https://gist.github.com/pathetic/e8309b978d42b15e0028

When serving pagespeed resources, I have observed the Cache-control header being set twice, and sometimes being shortened to a lifetime of 5 minutes. I am not sure why the latter occurs, it seems to be inconsistent.

Lastly, I have my keepalive timeout set to 65. When serving pagespeed resources, the Connection header is duplicated, once with the value "close" and again with the value "keep-alive."

Viewing the "source" resource without .pagespeed.xxx.ext shows all of these headers being set only once, and with the expiry always being set to 1 year in the future.

I can setup a demonstration for the issue or provide full configuration files if necessary.

**Comment by isaumya** [comment] 2016-07-13 12:40
Hi, I'm opening this again because I'm seeing the duplicate Vary: Accept Encoding

E.x.: https://www.isaumya.com/wp-includes,_js,_jquery,_jquery.js+wp-includes,_js,_jquery,_jquery-migrate.min.js+wp-content,_plugins,_disable-gravity-forms-fields,_disable-gf-fields.js.pagespeed.jc.FfybKwqn1o.js

```
HTTP/1.1 200 OK
Server: nginx centminmod
Content-Type: application/javascript
Connection: keep-alive
Date: Sat, 09 Jul 2016 17:45:50 GMT
Expires: Sun, 09 Jul 2017 17:45:50 GMT
Cache-Control: max-age=31536000
ETag: W/"0"
Last-Modified: Sat, 09 Jul 2016 17:45:50 GMT
X-Original-Content-Length: 110122
Vary: Accept-Encoding
Vary: Accept-Encoding
Content-Length: 110122
X-Page-Speed: 1.11.33.2-0
```

Here' my pagespeed config. 

```
pagespeed on;

#######################################################
# File cache settings 
######################################
# needs to exist and be writable by nginx

pagespeed FileCacheSizeKb          1024000;
pagespeed FileCacheCleanIntervalMs 3600000;
pagespeed FileCacheInodeLimit      5000000;
pagespeed LRUCacheKbPerProcess     81920;
pagespeed LRUCacheByteLimit        163840;

######################################################
# Mapping domain for HTTPS & Enabling HTTPS Fetch
######################################################

pagespeed LoadFromFileMatch "^https?://www.isaumya.com/" "/home/nginx/domains/isaumya.com/public/";
pagespeed LoadFromFileRuleMatch disallow .*;
pagespeed LoadFromFileRuleMatch allow \.css$;
pagespeed LoadFromFileRuleMatch allow \.jpe?g$;
pagespeed LoadFromFileRuleMatch allow \.png$;
pagespeed LoadFromFileRuleMatch allow \.gif$;
pagespeed LoadFromFileRuleMatch allow \.js$;
pagespeed Domain *.isaumya.com/*;
pagespeed Disallow */amp/*;

#######################################################
# By default, ngx_pagespeed adds an X-PageSpeed header with a value of the version of 
# ngx_pagespeed being used. This directive lets you specify the value to use instead:
# pagespeed XHeaderValue "ngx_pagespeed";

#######################################################
# let's speed up PageSpeed by storing it in the super duper fast memcached
# Ensure Memcached server installed http://centminmod.com/memcached.html
# default install for centmin mod is on port 11211, so localhost:11211 is correct
# uncomment - remove hash # in front of below 2 lines to enable
# timeout set at 100 milliseconds
#  pagespeed MemcachedThreads 1;
#  pagespeed MemcachedServers "localhost:11211";
#  pagespeed MemcachedTimeoutUs 100000;

#######################################################
## https://developers.google.com/speed/pagespeed/module/admin#virtual-hosts-and-stats
######################################
# pagespeed UsePerVhostStatistics on;

#######################################################
## 1.7.30.1 beta defaults
######################################
pagespeed PreserveUrlRelativity on;
pagespeed MaxCombinedCssBytes -1;
pagespeed ImageResolutionLimitBytes 16777216;
#pagespeed EnableFilters inline_google_font_css;

#######################################################
## 1.6.29.3 beta defaults
######################################
pagespeed AvoidRenamingIntrospectiveJavascript on;
pagespeed ImageInlineMaxBytes 3072;
pagespeed CssImageInlineMaxBytes 0;
pagespeed MaxInlinedPreviewImagesIndex -1;
pagespeed MinImageSizeLowResolutionBytes 3072;

#######################################################
## ngx_pagespeed filters settings below ##
######################################

# show half the users an optimized site, half the regular site
# change UA-XXXXXXXXXX-1 to your GA unique id
# uncomment - remove hash # in front of below 5 lines to enable
#  pagespeed RunExperiment on;
#  pagespeed AnalyticsID UA-XXXXXXXXXX-1;
#  pagespeed ExperimentVariable 1;
#  pagespeed ExperimentSpec "id=1;percent=50;level=CoreFilters;enabled=collapse_whitespace,remove_comments;";
#  pagespeed ExperimentSpec "id=2;percent=50";

# Filter settings
# https://developers.google.com/speed/pagespeed/module/filter-attribute-elide
pagespeed EnableFilters elide_attributes;

# https://developers.google.com/speed/pagespeed/module/filter-dedup-inlined-images
pagespeed EnableFilters dedup_inlined_images;

# filters outlined at http://ngxpagespeed.com/ngx_pagespeed_example/
pagespeed RewriteLevel CoreFilters;
pagespeed EnableFilters collapse_whitespace,remove_comments;

# make_google_analytics_async
# https://developers.google.com/speed/docs/mod_pagespeed/filter-make-google-analytics-async
pagespeed EnableFilters make_google_analytics_async;

# make_show_ads_async
# https://developers.google.com/speed/pagespeed/module/filter-make-show-ads-async
pagespeed EnableFilters make_show_ads_async;

# inline_google_font_css
# https://developers.google.com/speed/pagespeed/module/filter-css-inline-google-fonts
pagespeed EnableFilters inline_google_font_css;

# require FetchHttps if using https site
pagespeed FetchHttps enable;

# inline_css
# https://developers.google.com/speed/pagespeed/module/filter-css-inline
#   pagespeed EnableFilters inline_css;
#   pagespeed CssInlineMaxBytes 2048;

# prioritize_critical_css
# https://developers.google.com/speed/docs/mod_pagespeed/filter-prioritize-critical-css
pagespeed EnableFilters prioritize_critical_css;
#pagespeed CriticalImagesBeaconEnabled false;

# move_css_to_head
# https://developers.google.com/speed/docs/mod_pagespeed/filter-css-to-head
pagespeed EnableFilters move_css_to_head;

# move_css_above_scripts
# https://developers.google.com/speed/docs/mod_pagespeed/filter-css-above-scripts
pagespeed EnableFilters move_css_above_scripts;

# combine_css 
# https://developers.google.com/speed/docs/mod_pagespeed/filter-css-combine
pagespeed EnableFilters combine_css;

# Uncomment this if you want to prevent mod_pagespeed from combining files
# (e.g. CSS files) across paths
#
#  pagespeed CombineAcrossPaths off;

# combine_javascript
# https://developers.google.com/speed/docs/mod_pagespeed/filter-js-combine
pagespeed EnableFilters combine_javascript;
pagespeed MaxCombinedJsBytes 140000;
#pagespeed EnableFilters defer_javascript;

# extend_cache
# https://developers.google.com/speed/docs/mod_pagespeed/filter-cache-extend
pagespeed EnableFilters extend_cache;
pagespeed ForceCaching on;

# rewrite_css
# https://developers.google.com/speed/docs/mod_pagespeed/filter-css-rewrite
pagespeed EnableFilters rewrite_css;

# rewrite_javascript
# https://developers.google.com/speed/docs/mod_pagespeed/filter-js-minify
pagespeed EnableFilters rewrite_javascript;

# inline_preview_images
# https://developers.google.com/speed/pagespeed/module/filter-inline-preview-images
pagespeed EnableFilters inline_preview_images;

# resize_mobile_images
# https://developers.google.com/speed/pagespeed/module/filter-inline-preview-images#resize_mobile_images
pagespeed EnableFilters resize_mobile_images;
pagespeed MaxInlinedPreviewImagesIndex 6;
pagespeed MinImageSizeLowResolutionBytes 3072;

# lazyload_images
# https://developers.google.com/speed/docs/mod_pagespeed/filter-lazyload-images
# pagespeed EnableFilters lazyload_images;
# pagespeed LazyloadImagesAfterOnload off;

# rewrite_images
# https://developers.google.com/speed/docs/mod_pagespeed/filter-image-optimize
pagespeed EnableFilters rewrite_images;
pagespeed EnableFilters inline_images;
pagespeed EnableFilters recompress_images;
pagespeed EnableFilters jpeg_subsampling;
pagespeed EnableFilters convert_png_to_jpeg;
pagespeed EnableFilters resize_images;
pagespeed EnableFilters convert_jpeg_to_webp;
pagespeed EnableFilters convert_to_webp_lossless;

# convert_to_webp_animated
# https://developers.google.com/speed/pagespeed/module/filter-image-optimize#convert_to_webp_animated
pagespeed EnableFilters convert_to_webp_animated;

pagespeed EnableFilters insert_image_dimensions;

# responsive_images, responsive_images_zoom
# https://developers.google.com/speed/pagespeed/module/filter-image-responsive
pagespeed EnableFilters responsive_images;
pagespeed EnableFilters responsive_images_zoom;

#   pagespeed DisableFilters rewrite_images;
#   pagespeed DisableFilters recompress_images;
#   pagespeed DisableFilters convert_png_to_jpeg;
#   pagespeed DisableFilters extend_cache_images;

# sprite_images
# https://developers.google.com/speed/docs/mod_pagespeed/filter-image-sprite
pagespeed EnableFilters rewrite_css,sprite_images;

# insert_dns_prefetch
# https://developers.google.com/speed/docs/mod_pagespeed/filter-insert-dns-prefetch
pagespeed EnableFilters insert_dns_prefetch;

# InPlaceResourceOptimization
# https://developers.google.com/speed/pagespeed/module/system#ipro
# Enabled by default as of 1.9.32.1
pagespeed InPlaceResourceOptimization off;

#######################################################

```

Why is this happening. Due to this duplicate `Vary: Accept Encoding` pingdom is showing that `Accept Encoding` is not enabled on my server.

BTW I'm on the latest pagespeed build i.e. 1.11.33.2

Looking forward to help.

**Comment by oschaaf** [comment] 2016-07-14 11:15
@isaumya See https://github.com/pagespeed/ngx_pagespeed/issues/1064#issuecomment-205256619
From what I can tell, emitting multiple `Vary:` headers has been partially fixed in 1.11, and the full fix will be out in the next major release. 

To fix your problem right now, you can apply the following patch, which masks the symptoms (but does not fix the root cause):

```
diff --git a/src/ngx_pagespeed.cc b/src/ngx_pagespeed.cc
index 101e34e..e6f3126 100644
--- a/src/ngx_pagespeed.cc
+++ b/src/ngx_pagespeed.cc
@@ -609,6 +609,11 @@ ngx_int_t copy_response_headers_to_ngx(
     } else if (STR_EQ_LITERAL(name, "Vary") && value.len
         && STR_EQ_LITERAL(value, "Accept-Encoding")) {
       ps_request_ctx_t* ctx = ps_get_request_context(r);
+      // OS: temporary hack to fix multiple Vary: headers
+      // being received from PSOL
+      if (ctx->psol_vary_accept_only) {
+       continue;
+      }
       ctx->psol_vary_accept_only = true;
     }
 
```

**Comment by isaumya** [comment] 2016-07-14 11:17
OK, I will pass it to my server admin and will wait for the next major release.

**Comment by python273** [comment] 2016-08-19 13:39
OMG

NPS_VERSION=1.11.33.2

https://gist.github.com/python273/f1c8a48d744997fba679c8d2095b5eae
![screenshot from 2016-08-18 19 45 03 copy](https://cloud.githubusercontent.com/assets/3097956/17811336/3c320ccc-6633-11e6-89e9-c9b3b5c00a8d.png)

**Comment by huibaolin** [comment] 2016-08-19 14:26
@python273 We've fixed various issues about "Vary" header in the latest beta release, 1.11.33.3 (Release Notes: https://developers.google.com/speed/pagespeed/module/release_notes). Can you try it?

If the new release doesn't fix your problem. Can you give us a link to your website, so we can debug?

**Comment by jeffkaufman** [comment] 2016-08-23 12:54
I'm still seeing duplicate vary headers on ngx_pagespeed with 1.11.33.3:

```
$ headers www.jefftk.com/tmp.css?PageSpeed=off | grep Vary
Vary: Accept-Encoding
$ headers www.jefftk.com/tmp.css | grep Vary
Vary: Accept-Encoding
Vary: Accept-Encoding
```

**Comment by jeffkaufman** [comment] 2016-08-23 12:55
Looking at https://github.com/pagespeed/ngx_pagespeed/issues/1064 , this is expected behavior for 1.11.33.x and won't be fixed until the next major release.

**Closed by jeffkaufman** 2016-08-23 12:55 UTC
Labels: bug
