### ISSUE TITLE
Pagespeed + WP Super Cache not fetching

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1287] opened 2016-10-04 12:47 UTC
When I do the test on WP Super Cache, the caching shows as ok but then I got a message saying that the page can't be fetched. When I deactivate pagespeed it works, so I guess it's a problem of pagespeed not communicating with WP Supercache, this is the message I get : 

```
Test your cached website by clicking the test button below.

Fetching http://chinaboundltd.com/ to prime cache: OK

Fetching first copy of http://chinaboundltd.com/: OK (1.html)

Fetching second copy of http://chinaboundltd.com/: OK (2.html)

The pages do not match! Timestamps differ or were not found!
```

So WP super cache caches the HTML but pagespeed doesn't fetch it. Do you know how to fix this ?

Thanks

**Comment by jmarantz** [comment] 2016-10-04 12:52
I'm not clear on what symptom you are seeing.  What is the source of the messages in your bug description?  Is that some kind of website testing tool?

I don't necessarily expect an HTML page to be byte-equivalent every time it is viewed.  When ngx_pagespeed is running, it may optimize referenced resources in the background, and will change the URLs once they have been optimized.  This is expected behavior.

I think it makes sense for WP Super Cache to cache the output of WP because that avoids WP having to regenerate the HTML on every request.  But then PageSpeed may take a few seconds to complete the WP optimization.  If you fetch the HTML with a script three times very quickly, each fetch will have more URLs transformed until it converges once PageSpeed has cached the optimized versions of all the assets.

**Comment by chromafunk** [comment] 2016-10-04 13:02
The output I have pasted is the WP super cache testing tool within itself. When pagespeed is disabled, it gives an OK on the last line, meaning it has successfully fetched the cached html page. When I activate pagespeed I get this last line : 

```
The pages do not match! Timestamps differ or were not found!
```

I can't see if that is really happening or not because Pagespeed manipulates the final HTML output ... when I activate the debug on WP super cache, it should print debug messages on the HTML but I don't see it either. Something is telling me that it might not be working properly.

**Comment by hillsp** [comment] 2016-10-11 18:38
If you're still seeing 404s when PageSpeed is turned off, it sounds like you have some problem with Super Cache. Unfortunately, we can't help you with that.

I will say that with PageSpeed on, the "pages do not match" could happen if PageSpeed hasn't yet optimised all your images. I would expect that to go away after a few tries.

But like I said, it sounds like your main issue is the 404s, which are unrelated to PageSpeed. I'm going to close this issue.

**Closed by hillsp** 2016-10-11 18:38 UTC

**Comment by umrah876** [comment] 2017-01-15 05:49
First, is your website using CDN? If yes, it might be causing the problem. CDN sometimes conflict with WP Super Cache. This article might help https://www.msgdigital.com/wp-super-cache-tester-pages-not-match-fix/

I had that same issue and that is what I did to resolve my issue.
