### ISSUE TITLE
debug logging into seperate file for every vhost

### ISSUE THREAD

**Issue by ton31337** [pagespeed/ngx_pagespeed#817] opened 2014-09-27 11:53 UTC
Hey,

I see ngx_pagespeed itself do logging only to server_context file (global). Is it possible somehow to bypass this and set debug log for every vhost?

I tried to look into the source code, but there also is mentioned that debug is done in global error_log file only. I can change that this error_log file could be changed on request, but it will work not as expected. 

Is it possible that this feature will be in later versions of ngx_pagespeed?

D.

**Comment by jeffkaufman** [comment] 2015-01-30 16:04
Closing as a duplicate of [MPS#500](https://code.google.com/p/modpagespeed/issues/detail?id=500).

**Closed by jeffkaufman** 2015-01-30 16:04 UTC
