### ISSUE TITLE
Pagespeed breaks form submission?

### ISSUE THREAD

**Issue by amourinho** [pagespeed/ngx_pagespeed#1175] opened 2016-04-10 20:17 UTC
Even with simple code like this, pagespeed seems to break form submission.

<?
if(isset($_POST['submit'])){
        $name = $_POST['inName'];
}
echo "Hello " . $name;
?>
`<form method="post">
<input type="text" id="inName" name="inName"><button type="submit" id="submit" name="submit">Submit</button>
</form>
`

Does not work once pagespeed is enabled. Works properly when pagespeed disabled.
Tested on pagespeed versions: 1.10.33.6 and 1.11.33.0
Nginx version: 1.9.14

No error's are thrown by browser, or nginx. The page just times out. Any ideas on how to go about fixing this issue?

**Comment by jmarantz** [comment] 2016-04-10 21:01
Does it help to disable pagespeed on the form's submit urls via "pagespeed
disallow URL_WILDCARD:" ?

**Comment by oschaaf** [comment] 2016-04-10 21:23
I'm wondering if you can reproduce this on nginx `1.9.13`? Nginx `1.9.14` seems to contain some changes in the code that processes the request body (which is relevant for form submissions).

**Comment by amourinho** [comment] 2016-04-10 23:20
I switched to Nginx 1.9.13, seems to have fixed the issue. So there's some compatibility issue with their latest. Thanks for the ideas and help guys.

**Comment by nikolay** [comment] 2016-04-11 07:37
@oschaaf I wish Nginx truly followed SemVer! Patch versions more often than not are not backward compatible!

**Comment by oschaaf** [comment] 2016-04-12 21:46
I'm still  looking into this. I just noticed that with nginx 1.9.14, performing a POST via  HTTP/2 to a non-existing url will also result in a protocol violation, even when build without ngx_pagespeed. 
After some debugging I figured that out, as I was trying to make us not handle POST requests to `.pagespeed.` resources amongst others.

**Comment by oschaaf** [comment] 2016-04-12 22:12
The limit request module seems to suffer as well, and uses a similar flow to IPRO.
Posted to nginx-dev: https://forum.nginx.org/read.php?29,266134

**Comment by oschaaf** [comment] 2016-04-15 19:52
Update:
- An issue was filed at Chrome for this: https://bugs.chromium.org/p/chromium/issues/detail?id=603182
- NGINX added a workaround https://github.com/nginx/nginx/commit/7691b9750e0d3a2137e9d9188db65f7e39624b97

**Comment by Angristan** [comment] 2016-06-12 12:31
Any update ?

**Comment by jmarantz** [comment] 2016-06-12 12:58
The bug in Chrome has been assigned, but doesn't appear to have been updated for more than a month.

The workaround in nginx has been submitted (http://hg.nginx.org/nginx/rev/8df664ebe037).  Does that solve your problem for now?

**Comment by jeffkaufman** [comment] 2016-06-28 14:17
It looks like this is a bug in Chrome, Nginx has committed a workaround, and it doesn't make sense to fix this in PageSpeed.

**Closed by jeffkaufman** 2016-06-28 14:17 UTC
