### ISSUE TITLE
RespectXForwardedProto not working properly

### ISSUE THREAD

**Issue by mlimaloureiro** [pagespeed/ngx_pagespeed#1029] opened 2015-10-28 18:01 UTC
Hi this issue is very similar to this one https://github.com/pagespeed/ngx_pagespeed/issues/819.

My env consists in application servers (ec2 instances) behind an ELB where the ssl termination occur. So the HTTPS request is made to the load balancer, which then internally requests the EC2 instance over HTTP.

An example of what's happening is:

1. user makes a POST request over HTTPS.
2. the request reaches the application server over HTTP and is handled.
3. the redirect should go to an HTTPS url but it's coming in HTTP.

By reading the docs 

```
 pagespeed RespectXForwardedProto on;
```

should fix this issue but it's not working in my case. If I turn off pagespeed everything works well.

I currently have this in my config with pagespeed 1.9.32.10 version

```
    pagespeed on;
    pagespeed FileCachePath /var/ngx_pagespeed_cache;
    pagespeed EnableFilters lazyload_images;
    pagespeed CriticalImagesBeaconEnabled false;
    pagespeed RespectXForwardedProto on;
    pagespeed FileCacheSizeKb            153600;  # 150 MB
    pagespeed FileCacheCleanIntervalMs  3600000;  # 1 hour
    pagespeed FileCacheInodeLimit        500000;

    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
        add_header "" "";
    }
    location ~ "^/pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon$" { }
    location /ngx_pagespeed_statistics { allow 127.0.0.1; deny all; }
    location /ngx_pagespeed_message { allow 127.0.0.1; deny all; }
    location /pagespeed_console { allow 127.0.0.1; deny all; }
```

any help on this would be appreciated.

**Comment by oschaaf** [comment] 2015-10-28 18:28
@mlimaloureiro Could you try patching in https://github.com/pagespeed/ngx_pagespeed/commit/26a0c37b973a532b18f01c54f79598bd66bb546b to see if that fixes the problem?

**Comment by mlimaloureiro** [comment] 2015-10-29 10:04
thanks @oschaaf going to check

**Comment by mlimaloureiro** [comment] 2015-10-29 21:46
@oschaaf yep, works perfectly when patching https://github.com/pagespeed/ngx_pagespeed/commit/26a0c37b973a532b18f01c54f79598bd66bb546b any reason for this not being merged ?

**Comment by oschaaf** [comment] 2015-10-30 07:13
@mlimaloureiro Thanks for reporting back. I haven't made a pull request for this yet, because:
- I couldn't reproduce https://github.com/pagespeed/ngx_pagespeed/issues/819 in the exact same scenario, so I had a suspicion that this would fix it but wasn't 100% sure. Your confirmation helps greatly here.
- https://github.com/pagespeed/ngx_pagespeed/commit/26a0c37b973a532b18f01c54f79598bd66bb546b is an improvement in the way we handle the `Location:` response-header in ngx_pagespeed, but at the time I wasn't sure that it would be the best fix for the problem. Reconsidering the fix again, I think it's pretty reasonable.

I'll mark this issue as a duplicate and close it. I will also make a pull with the change you patched in soon, and continue tracking this in https://github.com/pagespeed/ngx_pagespeed/issues/819.

**Closed by oschaaf** 2015-10-30 07:13 UTC
Labels: duplicate
