### ISSUE TITLE
build raspbian RPI3

### ISSUE THREAD

**Issue by ezar** [pagespeed/ngx_pagespeed#1265] opened 2016-09-02 22:07 UTC
When we try to build, system fails. 
It's possible?
Regards,

**Comment by yeputons** [comment] 2016-09-02 22:08
Would you mind providing a little more information? What exactly fails? Which building instructions do you follow? What is in console output?

**Comment by ezar** [comment] 2016-09-02 22:56
I follow this instructions:
https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

Error:
> adding module in /home/pi/builds/nginx/build/ngx_pagespeed-release-1.11.33.3-beta
> Architecture not supported: armv7l

Seems we need to build PSOL for rpi3 arch? 
It's possible?

Regards,

**Comment by hillsp** [comment] 2016-09-06 17:49
We don't currently support building PSOL on ARM, as not many people want it. It is probably possible, but would not be a tiny amount of work.

**Comment by ezar** [comment] 2016-10-09 09:47
Why not many people want it?

**Comment by hillsp** [comment] 2016-10-10 17:06
Perhaps I should have said: As far as I know, this is if the first time anyone has asked for such support. I don't believe that many people are running webservers on an RPI.

**Comment by jeffkaufman** [comment] 2016-11-14 16:01
Closing as duplicate of https://github.com/pagespeed/ngx_pagespeed/issues/1213

**Closed by jeffkaufman** 2016-11-14 16:01 UTC

**Comment by Danrancan** [comment] 2023-01-04 21:40
> We don't currently support building PSOL on ARM, as not many people want it. It is probably possible, but would not be a tiny amount of work.

I want it and desperately need it. I'm stuck on Nginx 1.23.2 forever until these PSOL libraries are updated. If its work, tell me what I need to do to make this happen and I will work on it.

**Comment by yeputons** [comment] 2023-01-04 21:52
@Danrancan I think it may be better to open a new issue; it seems like no one subscribed to this issue works on the project anymore.

**Comment by Danrancan** [comment] 2023-01-05 00:26
> @Danrancan I think it may be better to open a new issue; it seems like no one subscribed to this issue works on the project anymore.

Thanks for the reply, I will open an issue then.
