### ISSUE TITLE
PageSpeed silently crashing returning partial web pages

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#965] opened 2015-05-07 22:13 UTC
We just upgraded WordPress to 4.2.2 and suddenly the edit page interface started to serve unfinished pages. When we append `?PageSpeed=Off` to the URL, the issue gets fixed, but, more importantly, we already have a rule that disables PageSpeed in the admin, i.e. `pagespeed Disallow "*/wp-admin/*";` but it doesn't seem to work. Any ideas, @jeffkaufman?

**Comment by oschaaf** [comment] 2015-05-11 07:10
@nikolay Is nginx really crashing? Or does something happen to the html that breaks wpadmin?

**Comment by jeffkaufman** [comment] 2015-05-11 11:03
When you say "unfinished" do you mean that the html gets cut off partway through, or just that the page doesn't entirely load.

Could you try loading it with PageSpeed on, with the network tab open in the developer tools, to check if any resource loads are failing?

**Comment by nikolay** [comment] 2015-05-11 16:28
@jeffkaufman @oschaaf I assume that it's crashing, but I'm not sure if that's really the case. The result is that the page source code is cut off part way and it works fine if I disable PageSpeed. I downgraded WordPress, so, it doesn't seem to be related to WordPress version, just the state of the particular page breaks PageSpeed as we don't have this issue on other pages.

**Comment by nikolay** [comment] 2015-05-11 16:41
Here's a sample: https://www.diffchecker.com/3j5qdhfz

BTW, I do have the URL for the sample above in the `pagespeed Disallow "*/wp-admin/*";`, but it seems that PageSpeed still does some processing and it's obviously not identical to `pagespeed off;`. I can find a specific workaround and make this particular page work, but the issue is that this race condition could happen on pages I haven't yet identified.

**Comment by oschaaf** [comment] 2015-05-12 08:39
@nikolay does anything noteworthy get logged to `error.log` when that happens?

**Comment by nikolay** [comment] 2015-05-12 08:43
@oschaaf Nothing. By the way, I removed `pagespeed Disallow "*/wp-admin/*";` and everything works. I think the pass-thru mode of disallowed routes hits some race condition or some buffering bug causes the buffer not to flush entirely.

**Comment by oschaaf** [comment] 2015-05-12 08:54
@nikolay You might be right about that. Looking at the code, the `Disallow` would disable IPRO but not html serialization/deserialization. 
We do, however, create and release an `NgxBaseFetch` instance for IPRO in this flow. 

I believe the extraneous events caused by the unused `NgxBaseFetch` instance could be responsible for the behaviour that you are seeing. I expect this to be fixed on `trunk-tracking`.

**Comment by nikolay** [comment] 2015-05-12 08:57
@oschaaf Thank you very much!

**Comment by nikolay** [comment] 2015-05-12 16:22
@oschaaf @jeffkaufman Unfortunately, it's not working for those pages even without `Disallow` again. Either it's not always working (i.e. there's some random element at play) or I didn't test properly, but the issue of `Disallow` not being a real pass-through is still there as behavior differs from `pagespeed off;` and it shouldn't.

**Comment by oschaaf** [comment] 2015-05-12 16:29
@nikolay I suspect this is fixed on trunk-tracking by https://github.com/pagespeed/ngx_pagespeed/commit/d0858790e4e76c45db8fc1ee549bb37c56d675e3
A partial backport might be possible, @jeffkaufman what do you think about doing that?

**Comment by oschaaf** [comment] 2015-05-12 16:32
pointed out the wrong commit, edited the previous post to correct that.

**Comment by nikolay** [comment] 2015-05-12 16:42
@oschaaf Do you think this is good enough to patch the latest stable with? Of course, I can do testing to validate, but if it works, can I venture into patching production servers with it?

**Comment by oschaaf** [comment] 2015-05-12 16:48
@nikolay 
I think that the required change to fix this carries little or no risk at all, but it needs to be extracted from the patch in included above as that includes a little more.
The change you need starts here: https://github.com/pagespeed/ngx_pagespeed/commit/a5411a1c7c23cdd587cfcf5f34376edd459421ba#diff-8fb776418fb480e5f084e8500b8f0b0cL1512 and ends here https://github.com/pagespeed/ngx_pagespeed/commit/a5411a1c7c23cdd587cfcf5f34376edd459421ba#diff-8fb776418fb480e5f084e8500b8f0b0cL1910
Care must be taken however, as master and trunk have diverged a bit, and think it might not apply cleanly.

**Comment by nikolay** [comment] 2015-05-12 17:00
So, to clarify, @oschaaf, I need to take parts of the commit (marked by you), not the full commit? Any idea when this whole thing will be released?

**Comment by oschaaf** [comment] 2015-05-12 17:04
@nikolay Yes, you need to take the marked part from the commit, and not the full commit.
I don't know much about the release eta

**Comment by jeffkaufman** [comment] 2015-05-12 17:15
@crowell is working on the release, but not all the fixes are ready.  Primarily the for pagespeed/mod_pagespeed/1048 .

**Comment by nikolay** [comment] 2015-05-12 17:37
@jeffkaufman Thanks for the heads up!

**Comment by crowell** [comment] 2015-05-12 18:02
added to list for 1.9.32.4 point release here https://github.com/pagespeed/mod_pagespeed/wiki/Release-1.9.32.4

**Comment by crowell** [comment] 2015-05-13 15:49
backported to master.

**Closed by crowell** 2015-05-13 15:49 UTC

**Comment by nikolay** [comment] 2015-05-13 18:00
@crowell Thank you, sir!

**Comment by nikolay** [comment] 2015-05-29 22:33
@crowell Any idea when 1.9.32.4 will be out?

**Comment by jeffkaufman** [comment] 2015-06-01 13:11
@nikolay We're working on it, but we want to include a fix for #1048.  We have a mitigation that we could ship, but if we can get the root cause fixed we'd much rather do that, and we're still debugging.

**Comment by nikolay** [comment] 2015-06-01 21:51
@jeffkaufman Thank you! Just asking for planning purposes. Will it work with Nginx 1.9?

**Comment by jeffkaufman** [comment] 2015-06-02 11:51
> Will it work with Nginx 1.9?

Yes, it should.  We test against nginx nightlies so that if nginx changes its API we know as far in advance as possible.
